export const ETHIOPIAN_BANK_METHOD_OPTIONS = [
  'Commercial Bank of Ethiopia (CBE)',
  'Awash Bank',
  'Dashen Bank',
  'Bank of Abyssinia',
  'Wegagen Bank',
  'Nib International Bank',
  'Cooperative Bank of Oromia',
  'Hibret Bank',
  'Abay Bank',
  'Zemen Bank',
  'Enat Bank',
  'Bunna Bank',
  'Berhan Bank',
  'Lion International Bank',
  'Oromia International Bank',
  'Tsehay Bank',
  'Siinqee Bank',
  'Goh Betoch Bank',
  'Hijra Bank',
  'Shabelle Bank',
  'CBE Birr',
  'Telebirr',
  'M-Pesa Ethiopia',
  'Amole Wallet',
  'HelloCash'
];
